# Generated by Django 6.0 on 2026-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_guest_game_host_role_game_room_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
